#!/bin/bash

INBOXDIR=/home/egegunes/var/INBOXDIR
JOURNAL=/home/egegunes/var/notes/journal.txt

for m in *.processed.md; do
    datetime=$(echo $m | awk -F '.' '{print $1}')
    echo $m
    timestamp=$(cat <<EOF | python
import datetime
s = "$datetime"
if s[9:11] == '24':
    s = "".join([*[s[0:9]], '0', '0', *[s[11:]]])
dt = datetime.datetime.strptime(s, "%d%m%YH%H%M%S")
print(int(dt.timestamp()))
EOF
)
    mv $m $timestamp.processed.md
done

for m in *.processed.md; do
    timestamp=$(echo $m | awk -F '.' '{print $1}')
    human=$(cat <<EOF | python
import datetime
dt = datetime.datetime.fromtimestamp($timestamp)
print(dt.isoformat())
EOF
)
    echo "$human" >> $JOURNAL
    echo "---" >> $JOURNAL
    cat $m >> $JOURNAL
    echo "---" >> $JOURNAL
done
