#!/bin/bash

INBOX_PATH=$HOME/var/INBOX
EDITOR=/usr/bin/vim

function commit {
    local mode=$1
    local file=$2

    cd $INBOX_PATH

    git pull
    git add $file
    git commit -m "$mode $file from $HOSTNAME"
    git push

    cd - &>/dev/null
}

function run_editor {
    local tmpfile=$(mktemp --suffix=".md")
    local timestamp=$(date +%d%m%YH%H%M%S)
    local filename="$timestamp.md"

    $EDITOR $tmpfile

    if [ $? != 0 ]; then
        echo "Discarding..."
        exit 1
    fi

    cp $tmpfile "$INBOX_PATH/$filename"
    commit "add" "$filename"
}

run_editor
