#!/usr/bin/env python3

import os


def walklevel(some_dir, level=1):
    some_dir = some_dir.rstrip(os.path.sep)
    assert os.path.isdir(some_dir)
    num_sep = some_dir.count(os.path.sep)
    for root, dirs, files in os.walk(some_dir):
        yield root, dirs, files
        num_sep_this = root.count(os.path.sep)
        if num_sep + level <= num_sep_this:
            del dirs[:]


if __name__ == "__main__":
    repo_dir = f"{os.getenv('HOME')}/src/"
    for root, dirs, files in walklevel(repo_dir, level=3):
        if root.count(os.path.sep) == 6:
            print(root[len(repo_dir):])
