#!/usr/bin/env python

import sys
import urllib.parse

if __name__ == "__main__":
    if len(sys.argv) < 2:
        arg = sys.stdin.read().strip()
    else:
        arg = sys.argv[1]

    try:
        print(urllib.parse.quote_plus(arg))
    except Exception as e:
        print("error: {}".format(e), file=sys.stderr)
        sys.exit(1)
